config/routes.rb
Rails.application.routes.draw do
  root to: 'noodles#index'

  resource :noodles do
    post :cook
  end
end

app/models/noodle.rb
class Noodle
  attr_accessor :cooking_time, :cooked

  def initialize(time, amp1, amp2)
    @time = time.to_i
    @amp1 = amp1.to_i
    @amp2 = amp2.to_i
  end

  def calculate
    # aux vars
    x, y = 1, 1

    # check equal values
    if @amp1 == @amp2
      @cooked = false
      return
    end

    while ((@amp1 * x - @amp2 * y).abs != @time) do
      # invalid data
      if (x * @amp1 == y * @amp2)
        @cooked = false
        return
      end

      # logic
    	if (x * @amp1 < y * @amp2)
        x += 1
    	else
        y += 1
    	end
    end

    @cooked = true
    @cooking_time = [x * @amp1, y * @amp2].max # multiply aux vars and amps to get max cooking time
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/noodles_controller.rb
class NoodlesController < ApplicationController
  def cook
    noddle = Noodle.new(params[:tempo], params[:amp1], params[:amp2])
    noddle.calculate

    if noddle.cooked
      flash[:success] = "O miojo deve ficar pronto em #{noddle.cooking_time} minutos :)"
    else
      flash[:error] = "Não é possível cozinhar o miojo :("
    end

    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(
        content_tag(:div) do
          content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} text-center") do
            concat message
          end
        end
      )
    end

    nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noodle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CDNs just for contest purpose -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/noodles/index.html.erb
<div class="container mt-5">
  <div class="row text-center">
    <div class="col-12">
      <img src="<%= asset_path('noodle.svg') %>" width="100" class="text-center" />
    </div>
  </div>

  <div class="row text-center mt-5">
    <div class="col-12">
      <%= flash_messages %>
    </div>
  </div>

  <div class="card mt-2">
    <div class="card-body">
      <%= form_tag cook_noodles_path do %>
        <div class="row">
          <div class="col">
            <input type="text" class="form-control" placeholder="Tempo de Preparo" name="tempo">
          </div>
          <div class="col">
            <input type="text" class="form-control" placeholder="Ampulheta 1" name="amp1">
          </div>
          <div class="col">
            <input type="text" class="form-control" placeholder="Ampulheta 2" name="amp2">
          </div>
          <div class="mr-3">
            <button type="submit" class="btn btn-primary">Preparar</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>